"""Report generation — PDF (ReportLab) and DOCX (python-docx). Pure Python, no external calls."""

import logging
import os
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

logger = logging.getLogger(__name__)


def generate_pdf(report_data: dict, output_path: str) -> str:
    """Generate compliance report as PDF. Returns output path."""
    doc = SimpleDocTemplate(output_path, pagesize=A4, topMargin=20 * mm, bottomMargin=20 * mm)
    styles = getSampleStyleSheet()
    elements = []

    # Title
    title_style = ParagraphStyle("CustomTitle", parent=styles["Title"], fontSize=18, textColor=colors.HexColor("#1a237e"))
    elements.append(Paragraph("LMPC 2011 Compliance Report", title_style))
    elements.append(Spacer(1, 8 * mm))

    # Header info
    info = report_data.get("info", {})
    header_data = [
        ["Product:", info.get("product_name", "N/A")],
        ["Date:", info.get("scan_date", datetime.now().strftime("%Y-%m-%d %H:%M"))],
        ["Officer:", info.get("officer_name", "N/A")],
        ["Score:", f"{report_data.get('score', 0)}/100"],
        ["Result:", report_data.get("pass_fail", "N/A")],
    ]
    header_table = Table(header_data, colWidths=[100, 350])
    header_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    elements.append(header_table)
    elements.append(Spacer(1, 8 * mm))

    # Violations table
    violations = report_data.get("missing_fields", []) + report_data.get("non_compliant_fields", [])
    if violations:
        elements.append(Paragraph("Violations Found", styles["Heading2"]))
        table_data = [["#", "Rule", "Field", "Issue", "Severity"]]
        for i, v in enumerate(violations, 1):
            table_data.append([
                str(i),
                v.get("rule_number", ""),
                v.get("field", ""),
                v.get("reason", ""),
                str(v.get("severity", "")),
            ])
        t = Table(table_data, colWidths=[30, 80, 90, 220, 50])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a237e")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
        ]))
        elements.append(t)
    else:
        elements.append(Paragraph("No violations found. All checked rules passed.", styles["Normal"]))

    elements.append(Spacer(1, 6 * mm))

    # Passed rules summary
    passed = report_data.get("passed_rules", [])
    if passed:
        elements.append(Paragraph("Passed Checks", styles["Heading2"]))
        for p in passed:
            elements.append(Paragraph(
                f"✓ {p['rule_number']} — {p['field']}: {p['reason']}", styles["Normal"]
            ))

    # Disclaimer
    elements.append(Spacer(1, 10 * mm))
    disc_style = ParagraphStyle("Disc", parent=styles["Normal"], fontSize=7, textColor=colors.grey)
    elements.append(Paragraph(
        "Generated by LMPC Compliance Scanner. Rule citations reference Legal Metrology (Packaged Commodities) Rules, 2011. "
        "This report is for inspection support only — final compliance determination rests with the authorized Legal Metrology officer.",
        disc_style,
    ))

    doc.build(elements)
    logger.info("PDF report generated at %s", output_path)
    return output_path


def generate_docx(report_data: dict, output_path: str) -> str:
    """Generate compliance report as DOCX. Returns output path."""
    doc = Document()

    # Title
    title = doc.add_heading("LMPC 2011 Compliance Report", level=0)
    for run in title.runs:
        run.font.color.rgb = RGBColor(0x1a, 0x23, 0x7e)

    # Header info
    info = report_data.get("info", {})
    p = doc.add_paragraph()
    p.add_run("Product: ").bold = True
    p.add_run(info.get("product_name", "N/A"))
    p = doc.add_paragraph()
    p.add_run("Date: ").bold = True
    p.add_run(info.get("scan_date", datetime.now().strftime("%Y-%m-%d %H:%M")))
    p = doc.add_paragraph()
    p.add_run("Officer: ").bold = True
    p.add_run(info.get("officer_name", "N/A"))
    p = doc.add_paragraph()
    p.add_run("Score: ").bold = True
    p.add_run(f"{report_data.get('score', 0)}/100")
    p = doc.add_paragraph()
    p.add_run("Result: ").bold = True
    result_text = report_data.get("pass_fail", "N/A")
    run = p.add_run(result_text)
    run.font.color.rgb = RGBColor(0x2e, 0x7d, 0x32) if result_text == "PASS" else RGBColor(0xc6, 0x28, 0x28)
    run.bold = True

    # Violations table
    violations = report_data.get("missing_fields", []) + report_data.get("non_compliant_fields", [])
    if violations:
        doc.add_heading("Violations Found", level=1)
        table = doc.add_table(rows=1, cols=5)
        table.style = "Light Grid Accent 1"
        headers = table.rows[0].cells
        for i, h in enumerate(["#", "Rule", "Field", "Issue", "Severity"]):
            headers[i].text = h
            for run in headers[i].paragraphs[0].runs:
                run.bold = True

        for idx, v in enumerate(violations, 1):
            row = table.add_row().cells
            row[0].text = str(idx)
            row[1].text = v.get("rule_number", "")
            row[2].text = v.get("field", "")
            row[3].text = v.get("reason", "")
            row[4].text = str(v.get("severity", ""))
    else:
        doc.add_heading("No Violations", level=1)
        doc.add_paragraph("All checked rules passed.")

    # Passed
    passed = report_data.get("passed_rules", [])
    if passed:
        doc.add_heading("Passed Checks", level=1)
        for p_item in passed:
            doc.add_paragraph(f"✓ {p_item['rule_number']} — {p_item['field']}: {p_item['reason']}")

    # Disclaimer
    doc.add_paragraph()
    p = doc.add_paragraph()
    run = p.add_run(
        "Generated by LMPC Compliance Scanner. Rule citations reference Legal Metrology (Packaged Commodities) Rules, 2011. "
        "This report is for inspection support only."
    )
    run.font.size = Pt(7)
    run.font.color.rgb = RGBColor(0x99, 0x99, 0x99)

    doc.save(output_path)
    logger.info("DOCX report generated at %s", output_path)
    return output_path
